config/routes.rb
Rails.application.routes.draw do
  resources :flats do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :reviews
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :flat
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :description, :address, :number_of_guests, :price_per_night)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_flat

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(flat_params)
    @review.flat = @flat

    if @review.save
      redirect_to flat_path(@flat.id)
    else
      render :new
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def flat_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit <strong><%= @flat.name %></strong></h1>

  <%= render 'form', flat: @flat %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>List of flats</h1>

  <% @flats.each do |flat| %>
    <%= link_to flat_path(flat) do %>
      <%= flat.name %>
    <% end %>
    <%= flat.address %>
    <%= flat.price_per_night %>
    <%= flat.number_of_guests %>
    <%= link_to "Delete", flat_path(flat), method: :delete %>
  <% end %>

</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a new flat</h1>

  <%= render 'form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1><%= @flat.name %></h1>
  <p><%= @flat.description %></p>
  <p><%= @flat.address %></p>
  <%= @flat.price_per_night %>
  <%= @flat.number_of_guests %>
  <%= link_to 'Add a review', new_flat_review_path(@flat) %>
  <br>
  <%= link_to "Edit", edit_flat_path(@flat), class: 'btn btn-primary' %>

  <% @flat.reviews.each do |review| %>
    <p><%= review.content %></p>
    <p><%= review.rating %></p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navigation">
  <p>Airbnb</p>
  <%= link_to "Add a flat", new_flat_path, class: "btn btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleAirbnb171</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Add add a review for <%= @flat.name %></h1>
  <%= simple_form_for([@flat, @review]) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: (1..5) %>
    <%= f.submit 'Add review' %>
  <% end %>
</div>